version: "3"
networks: 
        db_network:
services: 
    

    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - 8080:80
        links:
            - fpm
        volumes: 
            - ./src:/var/www/restful
        networks: 
            - db_network
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes: 
            - ./src:/var/www/restful
        links: 
            - mysql
        networks: 
            - db_network
    mysql:
        image: mysql:5.7
        ports: 
            - 33061:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=restful_db
        volumes:
            - ./database:/var/lib/mysql
        networks: 
            - db_network

    phpmyadmin:
        image: phpmyadmin
        depends_on: 
            - mysql
        restart: always
        ports:
            - 8081:80
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: mysql
        networks: 
            - db_network
